name: Frontend CI

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: 18.18.0
  IMAGE_REPO_NAME: frontend
  
jobs:
  lint:
    name: Lint Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          
      - name: Cache npm dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('starter/frontend/package-lock.json') }}
          
      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint -- --fix
          
  test:
    name: Test Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      
      - name: Cache npm dependencies
        id: cache-npm-test
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('starter/frontend/package-lock.json') }}
  
      - name: Install dependencies
        run: npm ci
  
      - name: Run tests
        run: CI=true npm test

  build:
    name: Build Job
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('starter/frontend/package-lock.json') }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build