name: Frontend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repository 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'repository/starter/frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: repository/starter/frontend

      - name: Run linting
        run: npm run lint
        working-directory: repository/starter/frontend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repository  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'repository/starter/frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: repository/starter/frontend

      - name: Run tests
        run: CI=true npm test
        working-directory: repository/starter/frontend

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repository 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'repository/starter/frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: repository/starter/frontend

      - name: Build application
        run: npm run build
        working-directory: repository/starter/frontend
